### ISSUE TITLE
successfully install but can't import

### ISSUE THREAD

**Issue by buptbubble** [meduz/LogGabor#2]
Thanks for amazing work. My python version is 2.7, and I installed LogGabor by pip (pip install LogGabor). It shows LogGabor was installed successfully. The site-packages folder has a new file called "LogGabor-0.2-py2.7.egg". When importing LogGabor in script, it can't find the modules. 
Could you help me solving the problem?

**Comment by buptbubble** [comment]
I download version 0.1.1. Now LogGabor can be imported. However there is another error...

Traceback (most recent call last):
  File "D:/myprograms/QoE/test.py", line 10, in <module>
    lg = LogGabor('default_param.py')
  File "build\bdist.win-amd64\egg\LogGabor\LogGabor.py", line 26, in __init__
AttributeError: 'str' object has no attribute 'pe'

do you have any idea about the problem?

**Comment by meduz** [comment]
Thanks for reporting the issue!

I have revamped the packaging. Can you try a ``pip install -U LogGabor`` and see if that now works? I just tried it on a docker VM and that works well. 5and this should also solve your second problem which was fixed later on.)

One recommended way of testing is to download and run the notebook available at http://nbviewer.jupyter.org/github/meduz/LogGabor/blob/master/LogGabor.ipynb .

Cheers,
Laurent

**Comment by buptbubble** [comment]
Thanks for your updating. It can be imported normally. But another error occurs in my scrips.
When I run `lg` = `LogGabor('default_param.py')`

The error is 

Traceback (most recent call last):
  File "D:/myprograms/QoE/test.py", line 10, in <module>
    lg = LogGabor('default_param.py')
  File "D:\myprograms\QoE\LogGabor.py", line 23, in __init__
    Image.__init__(self, pe)
  File "build\bdist.win-amd64\egg\SLIP\SLIP.py", line 115, in __init__
  File "build\bdist.win-amd64\egg\SLIP\SLIP.py", line 137, in get_pe
  File "C:\Anaconda2\lib\site-packages\NeuroTools\parameters\__init__.py", line 394, in __init__
    f = urlopen(initialiser)
  File "C:\Anaconda2\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Anaconda2\lib\urllib2.py", line 423, in open
    protocol = req.get_type()
  File "C:\Anaconda2\lib\urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: default_param.py

could you check again
many thanks!

**Comment by meduz** [comment]
Please check https://github.com/meduz/LogGabor/issues/4
