### ISSUE TITLE
error importing parameter file

### ISSUE THREAD

**Issue by meduz** [meduz/LogGabor#4]
(Moving comment from https://github.com/meduz/LogGabor/issues/2)

When I run lg = LogGabor('default_param.py')

The error is

```
Traceback (most recent call last):
File "D:/myprograms/QoE/test.py", line 10, in
lg = LogGabor('default_param.py')
File "D:\myprograms\QoE\LogGabor.py", line 23, in init
Image.init(self, pe)
File "build\bdist.win-amd64\egg\SLIP\SLIP.py", line 115, in init
File "build\bdist.win-amd64\egg\SLIP\SLIP.py", line 137, in get_pe
File "C:\Anaconda2\lib\site-packages\NeuroTools\parameters__init__.py", line 394, in init
f = urlopen(initialiser)
File "C:\Anaconda2\lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "C:\Anaconda2\lib\urllib2.py", line 423, in open
protocol = req.get_type()
File "C:\Anaconda2\lib\urllib2.py", line 285, in get_type
raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: default_param.py
```

could you check again
many thanks!

**Comment by meduz** [comment]
Indeed, the 'SLIP' library expects an URL such that the same will work with 'lg = LogGabor('file://default_param.py')'

Checkout [https://render.githubusercontent.com/view/ipynb?commit=d800629140d72744f23de1917aaebe5bf60106b1&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f626963762f534c49502f643830303632393134306437323734346632336465313931376161656265356266363031303662312f746573745f534c49502e6970796e62&nwo=bicv%2FSLIP&path=test_SLIP.ipynb&repository_id=47751638#initializing-the-SLIP-object](this notebook) for more examples as to how to initialize the library.

However, it was simple to add the feature of just loading using the filename and if you upgrade ('pip install -U LogGabor', this should now work. Can you please try it?

Laurent
